// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC3Dljv7Fpaz_9FRrV78rMjcIwb8pSX_aw',
    appId: '1:72571434294:web:6b4f98105edc9cb44f2f97',
    messagingSenderId: '72571434294',
    projectId: 'diario-de-treino',
    authDomain: 'diario-de-treino.firebaseapp.com',
    storageBucket: 'diario-de-treino.appspot.com',
    measurementId: 'G-CT1FPCGP9Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBNhDj7ZO4ehyGuG_QiV9C7Vv8V1VplPEs',
    appId: '1:72571434294:android:5c9d17a7a03ee44f4f2f97',
    messagingSenderId: '72571434294',
    projectId: 'diario-de-treino',
    storageBucket: 'diario-de-treino.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAPcZZoLr6aFfcJgfUVTe-MH_WJo0UeLOM',
    appId: '1:72571434294:ios:b188653204998a4f4f2f97',
    messagingSenderId: '72571434294',
    projectId: 'diario-de-treino',
    storageBucket: 'diario-de-treino.appspot.com',
    iosClientId: '72571434294-987hot3ieig5vla7d55hr1jrf56vmf6d.apps.googleusercontent.com',
    iosBundleId: 'com.example.projetoDiarioDeTreino',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAPcZZoLr6aFfcJgfUVTe-MH_WJo0UeLOM',
    appId: '1:72571434294:ios:93666518e16d39164f2f97',
    messagingSenderId: '72571434294',
    projectId: 'diario-de-treino',
    storageBucket: 'diario-de-treino.appspot.com',
    iosClientId: '72571434294-umaft6o40dasm4isjd4brea1190kpgrr.apps.googleusercontent.com',
    iosBundleId: 'com.example.projetoDiarioDeTreino.RunnerTests',
  );
}
